### ISSUE TITLE
How to make Fieldslib working? (OCaml 4.06.1)

### ISSUE THREAD

**Issue by RogerTarani** [janestreet/fieldslib#2]
RWO 2nd Edition promotes the use of Fieldslib (and ppx_fields_conv, depending both on ppxlib).
[First-Class Fields](https://dev.realworldocaml.org/records.html#scrollNav-6)

How to make Fieldslib working?

I'm using OCaml 4.06.1 and the required packages are installed:
```
$ opam list
fieldslib                   v0.11.0  Syntax extension to define first class valu
...
ppx_fields_conv          v0.11.0  Generation of accessor and iteration functi
ppxlib                        0.2.1  A comprehensive toolbox for ppx development
```
As well as required "base" v0.11.0, "jbuilder" 1.0+beta20 (req. build & >= "1.0+beta18.1"} and "ocaml-migrate-parsetree" 1.0.11 (req. >= "1.0").

Unfortunately, when trying the example of the book with utop,  I don't get the expected output (withall the helpers) 
```
# module Logon = struct
  type t =
    { session_id: string;
      time: Time_ns.t;
      user: string;
     credentials: string;
    }
  [@@deriving fields]
end;;
module Logon :
  sig
    type t = {
      session_id : string;
      time : Time_ns.t;
      user : string;
      credentials : string;
    }
  end
```
 I tried unsuccessfully:
```
# #require "fieldslib";;
# open Fieldslib;;
```
and other rather random directives and commands. 

What are the instructions for using Fieldslib (and ppx_fields_conv as well)?
Thanks

**Comment by yminsky** [comment]
Try to require ppx_fields_conv, which is the suntan extension itself. You can also require ppx_jane, which includes the full list of ppx extensions we use by default at Jane Street

**Comment by marctrem** [comment]
Requiring `ppx_fields_conv` worked for me. Thanks!
